<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <properties>
    <revision>0.1.0</revision>
    <changelist></changelist>

    <gpg.skip>true</gpg.skip>
    <publishable>false</publishable>
    <skipPublishing>true</skipPublishing>
    <spotless.skip>true</spotless.skip>
    <license.file>license-lgpl.txt</license.file>
    <licenseHeader.file>license-header-lgpl.txt</licenseHeader.file>

    <maven.install.skip>false</maven.install.skip>

    <maven.compiler.source>25</maven.compiler.source>
    <maven.compiler.target>25</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <name>Corexie</name>
  <description>A high-performance, predictable lifecycle framework for Java.</description>
  <licenses>
    <license>
      <name>GNU Lesser General Public License v3.0 only</name>
      <url>https://www.gnu.org/licenses/lgpl-3.0.html</url>
      <distribution>repo</distribution>
    </license>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <modules>
    <module>core</module>
    <module>example</module>
  </modules>
  <groupId>io.github.nullumie.corexie</groupId>
  <artifactId>corexie</artifactId>
  <version>${revision}${changelist}</version>
  <packaging>pom</packaging>

  <url>https://github.com/nullumie/corexie</url>

  <developers>
    <developer>
      <id>nullumie</id>
      <name>Nullumie</name>
      <url>https://github.com/nullumie</url>
    </developer>
  </developers>

  <scm>
    <url>https://github.com/nullumie/corexie</url>
    <connection>scm:git:https://github.com/nullumie/corexie.git</connection>
    <developerConnection>scm:git:ssh://github.com/nullumie/corexie.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jetbrains</groupId>
        <artifactId>annotations</artifactId>
        <version>26.1.0</version>
      </dependency>
      <dependency>
        <groupId>com.github.zafarkhaja</groupId>
        <artifactId>java-semver</artifactId>
        <version>0.10.2</version>
      </dependency>
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>2.25.4</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.17</version>
      </dependency>
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>2.25.4</version>
        <scope>compile</scope>
      </dependency>
      <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-slf4j2-impl</artifactId>
        <version>2.25.4</version>
        <scope>compile</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>

    <plugins>

      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <id>copy-and-rename-license</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <copy file="${maven.multiModuleProjectDirectory}/licenses/${license.file}"
                      tofile="${project.build.outputDirectory}/META-INF/LICENSE"
                      overwrite="true" />
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.7.3</version>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>3.4.0</version>
        <configuration>
          <licenseHeader>
            <file>${maven.multiModuleProjectDirectory}/licenses/${licenseHeader.file}</file>
            <delimiter>package</delimiter>
          </licenseHeader>
          <java>
            <googleJavaFormat>
              <style>AOSP</style>
            </googleJavaFormat>
            <importOrder />
            <removeUnusedImports />
          </java>
          <skip>${spotless.skip}</skip>
        </configuration>
        <executions>
          <execution>
            <id>spotless-check</id>
            <phase>validate</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.4.0</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <phase>package</phase>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>3.2.8</version>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <useAgent>true</useAgent>
          <skip>${gpg.skip}</skip>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>3.1.4</version>
        <configuration>
          <skip>${maven.install.skip}</skip>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>0.10.0</version>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>central</publishingServerId>
          <autoPublish>false</autoPublish>
          <waitUntil>validated</waitUntil>
          <skipPublishing>${skipPublishing}</skipPublishing>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>feature</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <spotless.skip>true</spotless.skip>
        <changelist>-SNAPSHOT</changelist>
        <gpg.skip>true</gpg.skip>
        <skipPublishing>true</skipPublishing>
      </properties>
    </profile>

    <profile>
      <id>integration</id>
      <properties>
        <spotless.skip>false</spotless.skip>
        <changelist>-SNAPSHOT</changelist>
        <gpg.skip>true</gpg.skip>
        <skipPublishing>false</skipPublishing>
      </properties>
    </profile>

    <profile>
      <id>production</id>
      <properties>
        <spotless.skip>false</spotless.skip>
        <changelist></changelist>
        <gpg.skip>false</gpg.skip>
        <skipPublishing>false</skipPublishing>
      </properties>
    </profile>
  </profiles>

</project>