name: Build, Test and Deploy (Integration)

on:
  push:
    branches:
      - dev
      - develop

jobs:
  push-branch-integration:
    name: Build, Test and Deploy (Integration)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build, Test and Deploy (Integration)
        run: mvn clean deploy -Pintegration -B -ntp
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}